packages:
  - docs
  - packages/*

catalog:
  '@roydukkey/eslint-config': ^4.0.2
  '@tsconfig/node20': ^20.1.5
  '@tsconfig/strictest': ^2.0.5
  '@types/node': ts5.8
  '@typescript-eslint/eslint-plugin': ^8.31.1
  '@typescript-eslint/parser': ^8.31.1
  '@vitest/coverage-v8': ^3.1.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.1.0
  autoprefixer: ^10.4.21
  clean-package: ^2.2.0
  conventional-changelog-cli: ^5.0.0
  conventional-changelog-conventionalcommits: ^8.0.0
  conventional-recommended-bump: ^11.0.0
  cspell: ^8.19.3
  del-cli: ^6.0.0
  escape-string-regexp: ^5.0.0
  eslint: ^9.25.0
  eslint-plugin-tsdoc: ^0.4.0
  eslint-plugin-vue: ^10.0.0
  fs-extra: ^11.3.0
  globals: ^16.0.0
  jsdom: ^26.1.0
  markdown-it-deflist: ^3.0.0
  npm-run-all2: ^7.0.2
  sass: ^1.87.0
  type-fest: ^4.40.1
  typescript: ~5.8.3
  typescript-eslint: ^8.31.1
  vite: ^6.3.3
  vite-svg-loader: ^5.1.0
  vitepress: 2.0.0-alpha.5
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.3
  web-features: ^2.34.1
