packages:
  - docs
  - packages/*

catalog:
  '@roydukkey/eslint-config': ^4.0.3
  '@tsconfig/node20': ^20.1.9
  '@tsconfig/strictest': ^2.0.8
  '@types/node': ts5.8
  '@typescript-eslint/eslint-plugin': ^8.59.0
  '@typescript-eslint/parser': ^8.59.0
  '@vitest/coverage-v8': ^4.1.5
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.2.1
  autoprefixer: ^10.5.0
  clean-package: ^2.2.0
  conventional-changelog: ^7.2.0
  conventional-changelog-conventionalcommits: ^9.3.1
  conventional-recommended-bump: ^11.2.0
  cspell: ^10.0.0
  del-cli: ^7.0.0
  escape-string-regexp: ^5.0.0
  eslint: ^9.25.0
  eslint-plugin-tsdoc: ^0.5.2
  eslint-plugin-vue: ^10.9.0
  fs-extra: ^11.3.4
  globals: ^17.5.0
  jsdom: ^29.0.2
  markdown-it-deflist: ^3.0.0
  npm-run-all2: ^8.0.4
  sass-embedded: ^1.99.0
  type-fest: ^4.41.0
  typescript: ~5.8.3
  typescript-eslint: ^8.59.0
  vite: ^8.0.9
  vite-svg-loader: ^5.1.1
  vitepress: 2.0.0-alpha.17
  vitest: ^4.1.5
  vue: ^3.5.33
  vue-eslint-parser: ^10.4.0
  web-features: ^3.24.0
